#SPDX-License-Identifier: MIT-0
---
# tasks file for monitoring
- name: Install Node Exporter
  package:
    name: node_exporter
    state: present

- name: Ensure Node Exporter is running
  service:
    name: node_exporter
    state: started
    enabled: true
